// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppLexicon.Models.Members.Data;

namespace WebAppLexicon.Migrations
{
    [DbContext(typeof(MemberDbContext))]
    [Migration("20220710073552_DbCreateIdentity")]
    partial class DbCreateIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "6ebd84e1-2904-44e4-9e71-833b1cf3ab44",
                            ConcurrencyStamp = "6ebd84e1-2904-44e4-9e71-833b1cf3ab44",
                            Name = "SuperAdmin",
                            NormalizedName = "SuperAdmin"
                        },
                        new
                        {
                            Id = "0c948f48-ae87-4f32-a2d4-d6d636351348",
                            ConcurrencyStamp = "0c948f48-ae87-4f32-a2d4-d6d636351348",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "e9aca773-8fc5-4c78-b8f1-5b96a0243839",
                            ConcurrencyStamp = "e9aca773-8fc5-4c78-b8f1-5b96a0243839",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "d9c54bc7-3222-4b52-bded-acab826bd957",
                            RoleId = "6ebd84e1-2904-44e4-9e71-833b1cf3ab44"
                        },
                        new
                        {
                            UserId = "557760d8-e19b-4dcd-97ae-8187ffccdf7a",
                            RoleId = "0c948f48-ae87-4f32-a2d4-d6d636351348"
                        },
                        new
                        {
                            UserId = "cb4b0c64-3ab5-4711-88f4-fd6ae9920070",
                            RoleId = "e9aca773-8fc5-4c78-b8f1-5b96a0243839"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WebAppLexicon.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Stockholm",
                            StateId = 5
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Helsingborg",
                            StateId = 2
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Växjö",
                            StateId = 1
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Gävle",
                            StateId = 4
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Visby",
                            StateId = 6
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "Berlin",
                            StateId = 7
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "Hamburg",
                            StateId = 9
                        },
                        new
                        {
                            CityId = 9,
                            CityName = "Lund",
                            StateId = 2
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "Munich",
                            StateId = 8
                        },
                        new
                        {
                            CityId = 10,
                            CityName = "Rome",
                            StateId = 10
                        },
                        new
                        {
                            CityId = 11,
                            CityName = "Paris",
                            StateId = 11
                        });
                });

            modelBuilder.Entity("WebAppLexicon.Models.Country", b =>
                {
                    b.Property<int>("CntyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CntyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CntyId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CntyId = 1,
                            CntyName = "Sweden"
                        },
                        new
                        {
                            CntyId = 2,
                            CntyName = "France"
                        },
                        new
                        {
                            CntyId = 3,
                            CntyName = "Italy"
                        },
                        new
                        {
                            CntyId = 4,
                            CntyName = "Germany"
                        });
                });

            modelBuilder.Entity("WebAppLexicon.Models.Members.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LangName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("WebAppLexicon.Models.Members.MemberLanguage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("MembersMemberId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LanguageId");

                    b.HasIndex("MembersMemberId");

                    b.ToTable("MemberLanguage");
                });

            modelBuilder.Entity("WebAppLexicon.Models.Members.Members", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CntyId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryCntyId")
                        .HasColumnType("int");

                    b.Property<int>("CtyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GovId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GovIdType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LangRead1")
                        .HasColumnType("int");

                    b.Property<int>("LangWrite1")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberApproval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MemberDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("memberType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryCntyId");

                    b.HasIndex("StateId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            Age = 30,
                            CntyId = 1,
                            CtyId = 3,
                            Email = "ggurnay0@opera.com",
                            FirstName = "Giustina",
                            Gender = "Genderfluid",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Gurnay",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Panamanian",
                            Phone = "108-553-0832",
                            StateId = 1
                        },
                        new
                        {
                            MemberId = 2,
                            Age = 76,
                            CntyId = 4,
                            CtyId = 7,
                            Email = "dkissick1@clickbank.net",
                            FirstName = "Danita",
                            Gender = "Female",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Kissick",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Iroquois",
                            Phone = "102-688-4545",
                            StateId = 8
                        },
                        new
                        {
                            MemberId = 3,
                            Age = 35,
                            CntyId = 1,
                            CtyId = 3,
                            Email = "cnoice2@wisc.edu",
                            FirstName = "Creigh",
                            Gender = "Male",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Noice",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Shoshone",
                            Phone = "934-181-5000",
                            StateId = 1
                        },
                        new
                        {
                            MemberId = 4,
                            Age = 67,
                            CntyId = 3,
                            CtyId = 10,
                            Email = "dhourihane3@toplist.cz",
                            FirstName = "Denis",
                            Gender = "Male",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Hourihane",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "American Indian and Alaska Native (AIAN)",
                            Phone = "260-684-7945",
                            StateId = 10
                        },
                        new
                        {
                            MemberId = 5,
                            Age = 62,
                            CntyId = 1,
                            CtyId = 2,
                            Email = "anattriss4@baidu.com",
                            FirstName = "Ariel",
                            Gender = "Male",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Nattriss",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Chickasaw",
                            Phone = "662-951-7611",
                            StateId = 2
                        },
                        new
                        {
                            MemberId = 6,
                            Age = 35,
                            CntyId = 4,
                            CtyId = 7,
                            Email = "tvelte5@nps.gov",
                            FirstName = "Tommie",
                            Gender = "Male",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Velte",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Filipino",
                            Phone = "474-732-2163",
                            StateId = 8
                        },
                        new
                        {
                            MemberId = 7,
                            Age = 40,
                            CntyId = 1,
                            CtyId = 3,
                            Email = "dgonzales6@yelp.com",
                            FirstName = "Dennison",
                            Gender = "Male",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Gonzales",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Puerto Rican",
                            Phone = "706-580-3696",
                            StateId = 1
                        },
                        new
                        {
                            MemberId = 8,
                            Age = 56,
                            CntyId = 3,
                            CtyId = 10,
                            Email = "tmorphet7@wix.com",
                            FirstName = "Tynan",
                            Gender = "Non-binary",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Morphet",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "White",
                            Phone = "298-108-6587",
                            StateId = 10
                        },
                        new
                        {
                            MemberId = 9,
                            Age = 33,
                            CntyId = 2,
                            CtyId = 11,
                            Email = "mfoulstone8@narod.ru",
                            FirstName = "Mischa",
                            Gender = "Male",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Foulstone",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Menominee",
                            Phone = "853-913-7659",
                            StateId = 11
                        },
                        new
                        {
                            MemberId = 10,
                            Age = 49,
                            CntyId = 1,
                            CtyId = 9,
                            Email = "lolczak9@spiegel.de",
                            FirstName = "Lisa",
                            Gender = "Female",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Olczak",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Vietnamese",
                            Phone = "225-320-9656",
                            StateId = 2
                        },
                        new
                        {
                            MemberId = 11,
                            Age = 38,
                            CntyId = 2,
                            CtyId = 11,
                            Email = "rgenningsa@bloglines.com",
                            FirstName = "Rancell",
                            Gender = "Genderfluid",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Gennings",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Tlingit-Haida",
                            Phone = "594-235-3927",
                            StateId = 11
                        },
                        new
                        {
                            MemberId = 12,
                            Age = 18,
                            CntyId = 1,
                            CtyId = 2,
                            Email = "kmonganb@1und1.de",
                            FirstName = "Kingsly",
                            Gender = "Male",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Mongan",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Yaqui",
                            Phone = "805-257-2819",
                            StateId = 2
                        },
                        new
                        {
                            MemberId = 13,
                            Age = 55,
                            CntyId = 2,
                            CtyId = 11,
                            Email = "sortellsc@yelp.com",
                            FirstName = "Sayer",
                            Gender = "Male",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Ortells",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Honduran",
                            Phone = "201-214-9764",
                            StateId = 11
                        },
                        new
                        {
                            MemberId = 14,
                            Age = 32,
                            CntyId = 4,
                            CtyId = 7,
                            Email = "aknotted@apache.org",
                            FirstName = "Abbie",
                            Gender = "Male",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Knotte",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Argentinian",
                            Phone = "870-289-5196",
                            StateId = 9
                        },
                        new
                        {
                            MemberId = 15,
                            Age = 90,
                            CntyId = 4,
                            CtyId = 7,
                            Email = "vputtrelle@nytimes.com",
                            FirstName = "Vilma",
                            Gender = "Polygender",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Puttrell",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Laotian",
                            Phone = "176-399-0215",
                            StateId = 9
                        },
                        new
                        {
                            MemberId = 16,
                            Age = 71,
                            CntyId = 1,
                            CtyId = 3,
                            Email = "abufferyf@jalbum.net",
                            FirstName = "Amber",
                            Gender = "Female",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Buffery",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Chilean",
                            Phone = "716-926-5332",
                            StateId = 1
                        },
                        new
                        {
                            MemberId = 17,
                            Age = 64,
                            CntyId = 1,
                            CtyId = 4,
                            Email = "wcolletg@a8.net",
                            FirstName = "Wiatt",
                            Gender = "Male",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Collet",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Chilean",
                            Phone = "369-361-2111",
                            StateId = 4
                        },
                        new
                        {
                            MemberId = 18,
                            Age = 18,
                            CntyId = 1,
                            CtyId = 9,
                            Email = "cgilstinh@ucla.edu",
                            FirstName = "Cacilia",
                            Gender = "Female",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Gilstin",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Cree",
                            Phone = "582-143-5937",
                            StateId = 2
                        },
                        new
                        {
                            MemberId = 19,
                            Age = 53,
                            CntyId = 4,
                            CtyId = 7,
                            Email = "lzecchiii@domainmarket.com",
                            FirstName = "Libbie",
                            Gender = "Female",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Zecchii",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Paiute",
                            Phone = "529-137-4269",
                            StateId = 9
                        },
                        new
                        {
                            MemberId = 20,
                            Age = 46,
                            CntyId = 3,
                            CtyId = 10,
                            Email = "clessliej@boston.com",
                            FirstName = "Cecilia",
                            Gender = "Female",
                            LangRead1 = 0,
                            LangWrite1 = 0,
                            LastName = "Lesslie",
                            MemberDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Tongan",
                            Phone = "358-511-7422",
                            StateId = 10
                        });
                });

            modelBuilder.Entity("WebAppLexicon.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CntyId")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateId");

                    b.HasIndex("CntyId");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            CntyId = 1,
                            StateName = "Kronoberg"
                        },
                        new
                        {
                            StateId = 2,
                            CntyId = 1,
                            StateName = "Skåne"
                        },
                        new
                        {
                            StateId = 3,
                            CntyId = 1,
                            StateName = "Uppsala"
                        },
                        new
                        {
                            StateId = 4,
                            CntyId = 1,
                            StateName = "Gäveborg"
                        },
                        new
                        {
                            StateId = 5,
                            CntyId = 1,
                            StateName = "Stockholm"
                        },
                        new
                        {
                            StateId = 6,
                            CntyId = 1,
                            StateName = "Gotland"
                        },
                        new
                        {
                            StateId = 7,
                            CntyId = 4,
                            StateName = "Berlin"
                        },
                        new
                        {
                            StateId = 8,
                            CntyId = 4,
                            StateName = "Bavaria"
                        },
                        new
                        {
                            StateId = 9,
                            CntyId = 4,
                            StateName = "Hamburg"
                        },
                        new
                        {
                            StateId = 10,
                            CntyId = 3,
                            StateName = "Lazio"
                        },
                        new
                        {
                            StateId = 11,
                            CntyId = 2,
                            StateName = "Île‑de‑France"
                        });
                });

            modelBuilder.Entity("WebAppLexicon.Models.Identity.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("UserRolesId")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("AppUser");

                    b.HasData(
                        new
                        {
                            Id = "d9c54bc7-3222-4b52-bded-acab826bd957",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea182049-e631-4368-827a-321ef60438b6",
                            Email = "superadmin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "SUPERADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEKohWAmaOphMqLY4+Vbq6hmW/Y41+CqyQhggpawqe0+Lc/sxm109x/BYq3JIkOAbbA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "87138a12-4135-40c8-90c4-12b2fb6719ae",
                            TwoFactorEnabled = false,
                            UserName = "SuperAdmin",
                            FirstName = "Louis",
                            LastName = "Lim",
                            MemberId = 9999,
                            UserRolesId = "6ebd84e1-2904-44e4-9e71-833b1cf3ab44"
                        },
                        new
                        {
                            Id = "557760d8-e19b-4dcd-97ae-8187ffccdf7a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7b5e1a2-c277-48b5-b464-321017fee71e",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEJsCSD75nE8UV6UtMIiR1/KsBaq9wlQRXpGyn7oUjXvRhwRwLwEfLCqhM2U8krjRBA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "370c3ff3-37f9-4a1d-acfa-e292d82c28b0",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            FirstName = "Vicient",
                            LastName = "Hook",
                            MemberId = 9998,
                            UserRolesId = "0c948f48-ae87-4f32-a2d4-d6d636351348"
                        },
                        new
                        {
                            Id = "cb4b0c64-3ab5-4711-88f4-fd6ae9920070",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0ca0d8b-7df4-4c92-a72d-612e11f0a866",
                            Email = "user1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAEAACcQAAAAEJgy26HaHKTJ3FdE99ei5ANmshYrO30v7SMY24BQBIIX7WbAhcjts8bHycnTple0Rg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "376011fe-2d07-43b5-9d64-7ad556149aca",
                            TwoFactorEnabled = false,
                            UserName = "User1",
                            FirstName = "Vicient",
                            LastName = "Kent",
                            MemberId = 0,
                            UserRolesId = "e9aca773-8fc5-4c78-b8f1-5b96a0243839"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAppLexicon.Models.City", b =>
                {
                    b.HasOne("WebAppLexicon.Models.State", "States")
                        .WithMany("Cities")
                        .HasForeignKey("StateId");
                });

            modelBuilder.Entity("WebAppLexicon.Models.Members.MemberLanguage", b =>
                {
                    b.HasOne("WebAppLexicon.Models.Members.Language", "Language")
                        .WithMany("MemberLanguage")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppLexicon.Models.Members.Members", "Members")
                        .WithMany("language1")
                        .HasForeignKey("MembersMemberId");
                });

            modelBuilder.Entity("WebAppLexicon.Models.Members.Members", b =>
                {
                    b.HasOne("WebAppLexicon.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("WebAppLexicon.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCntyId");

                    b.HasOne("WebAppLexicon.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAppLexicon.Models.State", b =>
                {
                    b.HasOne("WebAppLexicon.Models.Country", "Countries")
                        .WithMany("States")
                        .HasForeignKey("CntyId");
                });
#pragma warning restore 612, 618
        }
    }
}
